version: '3'
volumes:
    jenkins-docker-certs:
        driver: local
    jenkins-data:
        driver: local
networks:
  jenkins:
services:
    jenkins-docker:
        image: docker:dind
        container_name: jenkins-docker
        privileged: true
        networks:
            - jenkins
        environment:
            - DOCKER_TLS_CERTDIR=/certs
        volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client 
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "2376:2376"
        command: --storage-driver overlay2
        restart: always
    jenkins-blueocean:
        image: jenkins-blueocean:0.0.1-1 
        container_name: jenkins-blueocean
        networks:
            - jenkins
        environment:
            - DOCKER_HOST=tcp://jenkins-docker:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
        volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client:ro 
        ports:
            - "8080:8080"
            - "50000:50000"
        restart: on-failure

