version: '3.3'
services:
    jenkins-dind:
        ports:
            - '8080:8080'
            - '50000:50000'
        privileged: true
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'jenkins_home:/var/jenkins_home'
        image: jenkins-dind