version: '3.1'
networks:
  jenkins:
volumes:
  jenkins-data:
  jenkins-docker-certs:
services: 
  jenkins:
    depends_on:
      - docker
    image: jenkins-blueocean:0.0.1-1 
    container_name: jenkins
    restart: always
    networks:
      jenkins: {}
    ports:
      - 8080:8080
      - 50000:50000
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs:ro 
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_PATH}:/usr/bin/docker:ro
      - ${DOCKER_COMPOSE_PATH}:/usr/local/bin/docker-compose:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1 
  docker:
    image: docker:dind
    container_name: jenkins-agent
    privileged: true
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home 
      - ${DOCKER_PATH}:/usr/bin/docker:ro
      - ${DOCKER_COMPOSE_PATH}:/usr/local/bin/docker-compose:ro
    ports:
      - "2376:2376"
    environment:
      DOCKER_TLS_CERTDIR: /certs
    networks:
      jenkins:
        aliases:
          - docker