version: '3'
volumes:
    jenkins-docker-certs:
        driver: local
    jenkins-data:
        driver: local
networks:
  jenkins:
services:
    jenkins-blueocean:
        image: jenkins-blueocean:0.0.1-1 
        container_name: jenkins-blueocean
        networks:
            - jenkins 
        env_file:
            - .env
        volumes: 
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - ~/.ssh:/var/jenkins_home/.ssh 
            - ./startup.sh:/usr/local/bin/startup.sh:ro
        command: ["/usr/local/bin/startup.sh"]
        ports:
            - "8080:8080"
            - "50000:50000"
        restart: on-failure         