version: '3'
volumes:
    jenkins-docker-certs:
        driver: local
    jenkins-data:
        driver: local
networks:
  jenkins:
services:
    jenkins-blueocean:
        image: jenkins-blueocean:0.0.1-1 
        container_name: jenkins-blueocean
        networks:
            - jenkins 
        volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - ~/.ssh/id_rsa:/var/jenkins_home/.ssh/id_rsa
            - ~/.ssh/id_rsa.pub:/var/jenkins_home/.ssh/id_rsa.pub
            - ~/.ssh/known_hosts:/var/jenkins_home/.ssh/known_hosts
        ports:
            - "8080:8080"
            - "50000:50000"
        restart: on-failure

