version: '3'
volumes:
    jenkins-docker-certs:
        driver: local
    jenkins-data:
        driver: local
networks:
  jenkins:
environment:
    SSH_AUTH_SOCK: /ssh-agent
services:
    jenkins-blueocean:
        image: jenkins-blueocean:0.0.1-1 
        container_name: jenkins-blueocean
        networks:
            - jenkins 
        volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client:ro
            - /var/run/docker.sock:/var/run/docker.sock 
            - ${SSH_AUTH_SOCK}:/ssh-agent # Forward local machine SSH key to docker
        ports:
            - "8080:8080"
            - "50000:50000"
        restart: on-failure         